os: linux

dist: bionic

before_install:
  - sudo apt-get install -y debhelper libncurses-dev libpcre3-dev libssl-dev zlib1g-dev bison dpkg-dev
addons:
  apt:
    update: true

language: c
compiler: clang

script:
  - ./autogen.sh
  - ./configure HOMEMIXDIR='.Mix' GLOBALMIXCONF='/etc/mixmaster/client.conf'
  - scan-build -o "report/gcc" make CC=gcc
  - make clean
  - scan-build -o "report/clang" make CC=clang
  - CI/mk_index.sh

deploy:
  provider: pages
  cleanup: false
  local_dir: report/
  token: $GITHUB_TOKEN
  keep_history: false
  strategy: git
  verbose: true
  on:
    branch: master
  edge: true
