.TH MPGP 1 "Mixmaster Version 2.9.1"
.\" $Id: $
.SH NAME
mpgp \- Mixmaster PGP module tester
.SH SYNOPSIS
.B mpgp \fB\-e\fR [\fB\-b\fR] \fIkeyname\fR [\fIfilename\fR]
.PP
.B mpgp \fB\-s\fR [\fB\-b\fR] [\fIkeyname\fR [\fIfilename\fR]]
.PP
.B mpgp \fB\-c\fR [\fB\-b\fR] [\fIfilename\fR]
.PP
.B mpgp \fB\-C\fR [\fB\-b\fR] [\fIfilename\fR]
.PP
.B mpgp \fB\-d\fR [\fB\-b\fR] [\fIpassphrase\fR [\fIfilename\fR]]
.PP
.B mpgp \fB\-g\fR[\fBr\fR] \fIkeyname\fR [\fIbits\fR]
.PP
.B mpgp \fB\-a\fR[\fB+\-\fR] [\fB\-b\fR] [\fIfilename\fR]
.SH DESCRIPTION
Mixmaster is an anonymous remailer software. MPGP is a tester program
to diagnostic problems under PGP keys and messages handled by the
Mixmaster remailer software.
.PP
It can encrypts, decrypts and signs a message using the Mixmaster OpenPGP
library. The message is read from the standard input or the specified
\fIfilename\fR. The output will be written to the standard output. When
called without arguments it decrypts from the standard input. It asks for
a passphrase when needed.
.SH OPTIONS
.TP
.B "\-h"
Print a summary of command line options.
.TP
.B "\-e"
Encrypt a message with the first PGP key from the public key ring whose
contains \fIkeyname\fR as a substring.
.TP
.B "\-s"
Make a signature of the message with the first PGP key from the secret
key ring, or the first key whose contains \fIkeyname\fR as a substring if
specified.
.TP
.B "\-c"
Encrypt with symmetric cipher only.
.TP
.B "\-C"
Encrypt with symmetric cipher only using the new OpenPGP format.
.TP
.B "\-d"
Decrypt a message using \fIpassphrase\fR if specified or asking for it if
needed. It also verifies its signature.
.TP
.B "\-g\fR[\fBr\fR]"
Generate new PGP key pair with the given \fIkeyname\fR as user ID. If
\fBr\fR is specified the PGP key will be created using the RSA algorithm,
else with the ElGamal. \fIbits\fR is the key lenght and its default value
is 1024.
.TP
.B "\-a\fR[\fB+\-\fR]"
Create an ASCII PGP armored message. If \fB\-\fR is specified dearmor it.
.TP
.B "\-b"
Specifies that the message is in binary format.
.SH CONFIGURATION
The Mixmaster PGP module tester reads its configuration from the file
.B mix.cfg
in its working directory.  The configuration file consists of lines of
the type
.PP
.I VARIABLE       values
.PP
and of comments, which begin with a
.B #
character.
.PP
.TP
.B PGPPUBRING
Path to your public PGP key ring. Default:
.BR ~/.pgp/pubring.pgp .
(Windows default: PGP registry value.)
.TP
.B PGPSECRING
Path to your secret PGP key ring. Default:
.BR ~/.pgp/secring.pgp .
(Windows default: PGP registry value.)
.SH FILES
These filenames can be overridden by setting the corresponding configuration
option (given in parentheses).
.TP
.B mix.cfg
Mixmaster configuration file.
.TP
.B pubring.pgp
PGP public keys (\fBPGPPUBRING\fP).
.TP
.B secring.pgp
PGP secret keys (\fBPGPSECRING\fP).
.SH SEE ALSO
.BR mix (1),
.BR pgp (1),
.BR gpg (1).
.SH COPYRIGHT
(C) 1999-2002 Anonymizer Inc. and others.
Mixmaster may be redistributed and modified under certain conditions.
This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF
ANY KIND, either express or implied. See the file COPYRIGHT for
details.
